"""create klines table

Revision ID: e6b617e1f461
Revises: 
Create Date: 2026-06-26 14:24:38.814139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b617e1f461'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='股票名称'),
    sa.Column('date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Float(), nullable=False, comment='开盘价'),
    sa.Column('high', sa.Float(), nullable=False, comment='最高价'),
    sa.Column('low', sa.Float(), nullable=False, comment='最低价'),
    sa.Column('close', sa.Float(), nullable=False, comment='收盘价'),
    sa.Column('volume', sa.Float(), nullable=False, comment='成交量'),
    sa.Column('amount', sa.Float(), nullable=False, comment='成交额'),
    sa.Column('change_pct', sa.Float(), nullable=True, comment='涨跌幅(%)'),
    sa.Column('turnover_rate', sa.Float(), nullable=True, comment='换手率(%)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('klines')
    # ### end Alembic commands ###
